config/routes.rb
MoaiDocumentation::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :projects, only: [:show] do
    resources :doc_classes, only: [:show] do
      resources :doc_methods, only: [:show]
    end
  end
  

  root :to => 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/api_version.rb
class ApiVersion < ActiveRecord::Base
  attr_accessible :version_name, :project_id, :slug

  #validates :version_name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  belongs_to :project
  has_many :doc_classes

  def to_param
    slug
  end

  def to_s
    version_name
  end

end

app/models/doc_class.rb
class DocClass < ActiveRecord::Base
  attr_accessible :description, :name, :project_id
  belongs_to :project

  has_many :doc_methods

  default_scope order('name ASC')
  def to_s
    name
  end

  def to_param
    name
  end
end

app/models/doc_method.rb
class DocMethod < ActiveRecord::Base
  attr_accessible :doc_class_id, :description, :name
  belongs_to :doc_class

  def to_param
    name
  end

  def to_s
    name
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :slug, :description

  #validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  has_many :api_versions
  has_many :doc_classes
  
  def to_param
    slug
  end

  def to_s
    name
  end
end

app/controllers/api_versions_controller.rb
class ApiVersionsController < ApplicationController

  def show
    @project = Project.find_by_slug(params[:project_id])
    @version = ApiVersion.find_by_slug(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/doc_classes_controller.rb
class DocClassesController < ApplicationController

  def show
    @project = Project.find_by_slug(params[:project_id])
    @version = ApiVersion.find_by_slug(params[:api_version_id])
    @doc_class = DocClass.find_by_name(params[:id])
  end

end

app/controllers/doc_methods_controller.rb
class DocMethodsController < ApplicationController

  def show
    @project = Project.find_by_slug(params[:project_id])
    @version = ApiVersion.find_by_slug(params[:api_version_id])
    @doc_class = DocClass.find_by_name(params[:doc_class_id])
    @doc_method = DocMethod.find_by_name(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find_by_slug(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @projects = Project.all
  end

end

app/helpers/api_versions_helper.rb
module ApiVersionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doc_classes_helper.rb
module DocClassesHelper
end

app/helpers/doc_methods_helper.rb
module DocMethodsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/api_versions/show.html.haml
.row
  .span8
    %h1 #{@project.name} version #{@version.version_name}

.row
  .span6
    %h2 Classes
    %ul
    - @version.doc_classes.each do |doc_class|
      %li= link_to doc_class, project_api_version_doc_class_path(@project, @version, doc_class)

app/views/doc_classes/show.html.haml
.row
  .span8
    %h1= @doc_class

.row
  .span6
    = sanitize ( @doc_class.description )
  .span2
    %h5 Methods
    - @doc_class.doc_methods.each do |doc_method|
      = link_to doc_method, project_doc_class_doc_method_path(@project, @doc_class, doc_method)

%hr

= render partial: '/shared/disqus'

app/views/doc_methods/show.html.haml
.row
  .span8
    %h1 #{@doc_method}

.row
  .span6
    = sanitize ( @doc_method.description )

%hr

= render partial: '/shared/disqus'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Moai Docs"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Moai Docs", root_url, class: "brand"
          .container.nav-collapse
            %ul.nav
              - Project.all.each do |p|
                %li= link_to p.name, project_path(p)
            %form{ class: "navbar-form pull-right" } 
              %input{ type: "text", class: "span2" }
              %button{ type: "submit", class: "btn"} Search

    .container.content
      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          / .well.sidebar-nav
          /   %h3 Sidebar
          /   %ul.nav.nav-list
          /     %li.nav-header Sidebar
          /     %li= link_to "Link 1", "/path1"
          /     %li= link_to "Link 2", "/path2"
          /     %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Zipline Games 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/projects/show.html.haml
.row
  .span6
    %h1= @project.name
    %p= @project.description
  .span2
    %h3 Overview

.row
  .span6
    %h2 Classes
    %ul
    - @project.doc_classes.each do |doc_class|
      %li= link_to doc_class, project_doc_class_path(@project, doc_class)

app/views/shared/_disqus.html.haml
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'moaidocumentation'; // Required - Replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

%noscript Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>

app/views/welcome/index.html.haml
%h1 Welcome to Moai Docs!

%h2 Choose a project

- @projects.each do |project|
  %h3= link_to project, project_path(project)

%p If you find a bug in the docs please report them to #{ link_to "moaisupport@ziplinegames.com", "mailto:moaisupport@ziplinegames.com" }